export const PROJECT_BEGIN = "GETTING_PROJECTS_BEGIN";
export const PROJECT_ERROR = "GETTING_PROJECTS_ERROR";
export const QUERY_PROJECTS_SUCCESS = "GETTING_PROJECTS_SUCCESS";
export const PROJECT_SAVED = "PROJECT_SAVED";
