export const MANAGEMENT_DASHBOARD_BEGIN = 'MANAGEMENT_DASHBOARD_BEGIN';
export const MANAGEMENT_DASHBOARD_ERROR = 'MANAGEMENT_DASHBOARD_ERROR';
export const QUERY_MANAGEMENT_DASHBOARD_SUCCESS = 'QUERY_MANAGEMENT_DASHBOARD_SUCCESS';
