export const QUERY_SUPPLIER_SUCCESS = 'QUERY_SUPPLIER_SUCCESS';
export const SUPPLIER_BEGIN = 'SUPPLIER_BEGIN';
export const SUPPLIER_ERROR = 'SUPPLIER_ERROR';
export const ADD_SUPPLIER = 'ADD_SUPPLIER';
export const EDIT_SUPPLIER = 'EDIT_SUPPLIER';
export const CANCEL_SUPPLIER = 'CANCEL_SUPPLIER';
export const SUPPLIER_SAVED = 'SUPPLIER_SAVED';
export const GET_SUPPLIER_SUCCESS = 'GET_SUPPLIER_SUCCESS';

export const EMPLOYEE_SAVED = 'EMPLOYEE_SAVED';