/* Dashboard events */
export const DASHBOARD_DELETE_APPOINTMENT = "DASHBOARD_DELETE_APPOINTMENT";
export const DASHBOARD_LOAD_DASHBOARD = "DASHBOARD_LOAD_DASHBOARD";
export const DASHBOARD_REFRESH_TIMER = "DASHBOARD_REFRESH_TIMER";
export const DASHBOARD_BEGIN = "DASHBOARD_BEGIN";
export const DASHBOARD_ERROR = "DASHBOARD_ERROR";
export const APPOINTMENT_SUCCESS = 'APPOINTMENT_SUCCESS';


export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const EDIT_APPOINTMENT = "EDIT_APPOINTMENT";
export const CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT";