export const CUSTOMER_BEGIN = 'CUSTOMER_BEGIN';
export const QUERY_CUSTOMER_SUCCESS = 'QUERY_CUSTOMER_SUCCESS';
export const CUSTOMER_ERROR = 'CUSTOMER_ERROR';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const CUSTOMER_SAVED = 'CUSTOMER_SAVED';
