export const PAYMENT_BEGIN = 'PAYMENT_BEGIN';
export const PAYMENT_ERROR = 'PAYMENT_ERROR';
export const QUERY_PAYMENT_SUCCESS = 'QUERY_PAYMENT_SUCCESS';
export const PAYMENT_REQUEST_INVOICES_SUCCESS = 'PAYMENT_REQUEST_INVOICES_SUCCESS';
