export const ENTRY_BEGIN = 'ENTRY_BEGIN';
export const ENTRIES_ERROR = 'ENTRIES_ERROR';
export const QUERY_ENTRIES_SUCCESS = 'QUERY_ENTRIES_SUCCESS';
export const APPROVE_ENTRY_SUCCESS = 'APPROVE_ENTRY_SUCCESS';
export const CHECK_ENTRY = 'CHECK_ENTRY';
export const CHECK_ALL_ENTRIES = 'CHECK_ALL_ENTRIES';
