export const REPORT_BEGIN = "REPORT_BEGIN";
export const REPORT_ERROR = "REPORT_ERROR";
export const PROJECT_REPORT_QUERY_SUCCESS = 'PROJECT_REPORT_QUERY_SUCCESS';
export const TIME_REPORT_QUERY_SUCCESS = 'TIME_REPORT_QUERY_SUCCESS';
