export const APPLICATION_BEGIN = "APPLICATION_BEGIN";
export const LOAD_CONFIGURATION = "LOAD_CONFIGURATION";
export const APPLICATION_ERROR = "APPLICATION_ERROR";

export const SAVE_ACCOUNT = 'SAVE_ACCOUNT';
